# Generated by Django 3.2 on 2022-08-20 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_join',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 9, 22, 17, 150629, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.province', verbose_name='province'),
        ),
    ]
