# Generated by Django 3.2 on 2022-08-22 07:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220820_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 7, 7, 4, 640745, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
