# Generated by Django 3.2 on 2022-08-22 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 7, 23, 59, 278069, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
