# Generated by Django 3.2 on 2022-08-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=True, upload_to='files/%y/%m/%d', verbose_name='file'),
        ),
    ]
